### ISSUE TITLE
Able to Create Server with No Server Access Rights

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/ReleaseEngineer#139]
Create a new Group within a specific Domain-> Make sure there are no Access Rights to anything for the new Group -> Add a new User, then add the User to the Group within the Domain -> Log out and log back in as the new User -> Click on the Domain -> Click on each menu along the top and right click on the Domain, notice there are no "Create New <object>" drop down menus appearing, as expected.  However, clicking on the Servers menu and right clicking on the Domain causes a "New Server for this Domain" to appear. A Server can be created.

**Comment by rightker** [comment]
Same problem exists for Build Engines.

**Comment by pgibbs-openmake** [comment]
Should be fixed, retest required.

**Comment by rightker** [comment]
Not fixed, works the same as before, able to create a Server without creation rights.

**Comment by rightker** [comment]
Tested, fixed, closing this issue.

**Comment by pgibbs-openmake** [comment]
Closing this
